version: "3.9"

services:
  milvus-standalone:
    build: .
    container_name: milvus-standalone
    restart: unless-stopped
    security_opt:
      - seccomp:unconfined
    environment:
      ETCD_USE_EMBED: "true"
      ETCD_DATA_DIR: "/var/lib/milvus/etcd"
      ETCD_CONFIG_PATH: "/milvus/configs/embedEtcd.yaml"
      COMMON_STORAGETYPE: "local"
      DEPLOY_MODE: "STANDALONE"
      MINIO_ADDRESS: "localhost:9000"
      MINIO_USE_SSL: "false"
      COMMON_SECURITY_AUTHORIZATIONENABLED: "false"
      LOCAL_STORAGE_PATH: "/var/lib/milvus/data"
      QUERYNODE_LOCAL_PATH: "/var/lib/milvus/data/querynode"
      DATANODE_LOCAL_PATH: "/var/lib/milvus/data/datanode"
      INDEXNODE_LOCAL_PATH: "/var/lib/milvus/data/indexnode"
    ports:
      - "19530:19530"
      - "9091:9091"
      - "2379:2379"
    volumes:
      - ../../volumes/milvus:/var/lib/milvus
      - ./embedEtcd.yaml:/milvus/configs/embedEtcd.yaml
      - ./user.yaml:/milvus/configs/user.yaml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9091/healthz"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 90s
